### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by d-gubert** [darkeyedevelopers/natural-cron.js#4]
Hello :)

First of all, congrats on the lib, it's very handy!

We are looking to use it as a parser for our [Scheduler functionality on the Rocket.Chat Apps-Engine project](https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/89), and we were wondering if there are any plans on adding support for other language inputs as well? Or if there's an idea how this would be done?

I've tried simply translating the words used in the regexes to Portuguese but that didn't work :joy: I'm not familiar with NLP but considering the differences between the two languages I think more changes would be needed.

**Comment by RathiRohit** [comment]
Currently there is no plan for supporting other languages.
Current core implementation of the lib is not flexible enough to support such changes. As you already figured out, just changing the words in regexes will certainly not work as expected.

I am planning to work on reimplementing the whole library from scratch in a better way, I will see if it would be possible to make it extensible for other languages in some way during that. But can't promise anything on this front.

As of now, there is no feasible way to add support for other languages.
