### ISSUE TITLE
Publishing the latest version to npm

### ISSUE THREAD

**Issue by valekjo** [darkeyedevelopers/natural-cron.js#7]
Hi. The library looks great and I'd like to use it in our project, but I am blocked by import of `readline` - which has been fixed in master but is not published in latest version available from npm (1.0.2).

Would it be possible to publish the current master to npm?

Thanks!

**Comment by RathiRohit** [comment]
Thanks @valekjo for pointing this out. New version is now published to npm. (v1.1.0 🚀)
